# 序言 {.unnumbered}

欢迎来到 "R 数据科学（第二版）"！
该版在第一版的基础上做了一些重要修订，删除了我们认为不再有用的内容，增加了原本打算写进第一版的内容，并对文本和代码进行了整体更新，以反映最佳实践中的变化。同
时，我们也很高兴迎来一位新的合著者Mine Çetinkaya-Rundel，他是一位著名的数据科学教育工作者，也是我们在Posit(前身为RStudio)公司的一位同事。

以下是这些重要变化的概述：

-   本书第一部分已更名为“全局游戏” （Whole game）。这
    部分的目的是在深入细节之前先为读者提供数据科学“全局游戏” 的大致情况。

-   本书第二部分称为“可视化”（Visualize）。和
    第一版相比，这部分对数据可视化工具和最佳实践进行了更为全面的介绍。虽
    然要获取所有详细信息仍需参考名为 [ggplot2](http://ggplot2-book.org/)的书, 但第二版已涵盖了很多最重要的可视化技术。

-   本书第三部分称为“转换”（Transform）。这
    部分增加了关于数字、逻辑向量和缺失值的新章节，这些之前都是数据转换章节的一部分，但现在需要更多的篇幅来覆盖所有细节。

-   本书第四部分称为“导入”（Import）。这
    是一组新章节，包括读取纯文本文件和电子表格，从数据库中获取数据、处理大数据、将层次结构数据转换为矩形数据，以及从网站抓取数据。

-   “编程”（Program）部分保持不变，但已被从头至尾重写，聚焦于函数编写和迭代的最重要部分。函
    数编写现在包含了如何封装tidyverse函数（处理tidy评估的挑战）的详细信息，因为这在过去几年中变得更容易、更重要。我
    们还增加了一个base 包重要函数的新章节，这些函数你可能在实际遇到的R代码中看到。

-   "建模"（Modeling）部分已被删除。我
    们之前没有足够的篇幅来全面深入地讲解建模，但现在已经有更好的资源可供选择。我
    们一般推荐使用[tidymodels](https://www.tidymodels.org/) 包，并推荐阅读由Max Kuhn和Julia Silge撰写的[Tidy Modeling with R](https://www.tmwr.org/)一书。

-   “交流”（Communicate）部分依然保留，但已全面更新。本
    书第二版利用[Quarto](https://quarto.org/)编写，而不是R Markdown，Quarto被看作是更具应用前景的工具。
